FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY src/ src/
COPY resources/ resources/

CMD ["celery", "-A", "src.services.orchestrator_worker", "worker", "--loglevel=info", "-Q", "celery"]
